import React from 'react';
import { Link } from 'react-router-dom';

const TermsPage: React.FC = () => (
  <div style={{ padding: 40, maxWidth: 800, margin: '0 auto', color: 'var(--text-primary)', lineHeight: 1.6, height: '100vh', overflowY: 'auto' }}>
    <Link to="/" style={{ color: 'var(--primary-light)', textDecoration: 'none', marginBottom: 20, display: 'inline-block' }}>← Back</Link>
    <h1>Terms of Service</h1>
    <p>Last updated: July 2026</p>
    
    <section style={{ marginTop: 30 }}>
      <h2>1. Acceptance of Terms</h2>
      <p>By accessing and using KymiraAI, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.</p>
    </section>

    <section style={{ marginTop: 30 }}>
      <h2>2. Use of Service</h2>
      <p>You agree to use KymiraAI in compliance with the Information Technology Act, 2000 (India) and all other applicable laws. You shall not use the service to transmit offensive, illegal, or harmful content.</p>
    </section>
    
    <section style={{ marginTop: 30 }}>
      <h2>3. Intellectual Property</h2>
      <p>All intellectual property rights in the service belong to us. The content generated by the AI may be subject to the terms of the respective model providers (e.g., OpenRouter, OpenAI).</p>
    </section>
    
    <section style={{ marginTop: 30 }}>
      <h2>4. Limitation of Liability</h2>
      <p>KymiraAI is provided "as is" without any warranties. We shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>
    </section>

    <section style={{ marginTop: 30 }}>
      <h2>5. Governing Law and Jurisdiction</h2>
      <p>These terms shall be governed by and construed in accordance with the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in India.</p>
    </section>

    <section style={{ marginTop: 30 }}>
      <h2>6. Contact Us</h2>
      <p>For any questions or concerns regarding these Terms, please contact us at: <strong>hello@isharankumar.com</strong>.</p>
    </section>
  </div>
);

export default TermsPage;
